# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20180516_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
