# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likesbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(related_name='books', to='likesbooks.User'),
        ),
    ]
