# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-18 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likesbooks', '0002_book_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_by_users',
            field=models.ManyToManyField(related_name='liked_books', to='likesbooks.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to='likesbooks.User'),
            preserve_default=False,
        ),
    ]
