# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltreviewer', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='review',
            name='book_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beltreviewer.Book'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_book', to='beltreviewer.User'),
        ),
    ]
